Bootstrap: docker
From: alpine:latest

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY http://gitub.com/pscedu/singularity-fdupes
    COPYRIGHT Copyright © 2025 Pittsburgh Supercomputing Center. All Rights Reserved.
    VERSION 2.4.0

%post
    apk update
    apk add fdupes

%runscript
    fdupes "$@"
